# Generated by Django 4.1.7 on 2023-05-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.IntegerField()),
                ('b2', models.IntegerField()),
                ('b3', models.IntegerField()),
            ],
        ),
    ]
