# Generated by Django 4.1.7 on 2023-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0002_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='b1',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='b2',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='b3',
        ),
        migrations.AddField(
            model_name='likes',
            name='bird',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
