# Generated by Django 4.1.7 on 2023-05-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalkulator', '0003_rename_b1_likes_count_remove_likes_b2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='count',
            new_name='likes',
        ),
    ]
